/*
Container Tracking API

Testing UploadContainersForTrackingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package portcast

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/buyco/go-portcast-sdk/portcast"
)

func Test_portcast_UploadContainersForTrackingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UploadContainersForTrackingAPIService PostBooking", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UploadContainersForTrackingAPI.PostBooking(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadContainersForTrackingAPIService PostEtaBillOfLadingBookmarks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UploadContainersForTrackingAPI.PostEtaBillOfLadingBookmarks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
