/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the GetApiV1EtaBillOfLadingBookmarksTerminals403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiV1EtaBillOfLadingBookmarksTerminals403Response{}

// GetApiV1EtaBillOfLadingBookmarksTerminals403Response struct for GetApiV1EtaBillOfLadingBookmarksTerminals403Response
type GetApiV1EtaBillOfLadingBookmarksTerminals403Response struct {
	Error *string `json:"error,omitempty"`
}

// NewGetApiV1EtaBillOfLadingBookmarksTerminals403Response instantiates a new GetApiV1EtaBillOfLadingBookmarksTerminals403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiV1EtaBillOfLadingBookmarksTerminals403Response() *GetApiV1EtaBillOfLadingBookmarksTerminals403Response {
	this := GetApiV1EtaBillOfLadingBookmarksTerminals403Response{}
	var error_ string = "Terminal API not enabled for this account"
	this.Error = &error_
	return &this
}

// NewGetApiV1EtaBillOfLadingBookmarksTerminals403ResponseWithDefaults instantiates a new GetApiV1EtaBillOfLadingBookmarksTerminals403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiV1EtaBillOfLadingBookmarksTerminals403ResponseWithDefaults() *GetApiV1EtaBillOfLadingBookmarksTerminals403Response {
	this := GetApiV1EtaBillOfLadingBookmarksTerminals403Response{}
	var error_ string = "Terminal API not enabled for this account"
	this.Error = &error_
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) SetError(v string) {
	o.Error = &v
}

func (o GetApiV1EtaBillOfLadingBookmarksTerminals403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiV1EtaBillOfLadingBookmarksTerminals403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response struct {
	value *GetApiV1EtaBillOfLadingBookmarksTerminals403Response
	isSet bool
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) Get() *GetApiV1EtaBillOfLadingBookmarksTerminals403Response {
	return v.value
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) Set(val *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response(val *GetApiV1EtaBillOfLadingBookmarksTerminals403Response) *NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response {
	return &NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response{value: val, isSet: true}
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


