/*
Portcast API (1.1.0) - Bill of Lading Tracking

**This documentation is for the latest version of the Portcast Bill of Lading Tracking API.**  There are two variables used in this documentation: 1. `api-url`: the url to use for accessing the API. The official url is `https://api.portcast.io` 2. `x-api-key`: the access token to send along with every request to the API. This key will be provided to each organisation upon API access activation  The general workflow is as below:  1. Create the bill of lading bookmark if it does not exist already (`POST {{api-url}}/api/v1/eta/bill-of-lading-bookmarks`). 2. A bookmark must contain `carrier_no`, `bl_no` and `cntr_no` information. This will return the bill of lading bookmark information created. Record the `id` field from the response. 3. Wait for predictions to be generated. This could take up to 5 mins. 5. Query for the tracking results based on the `id` recorded earlier (`GET {{api-url}}/api/v1/eta/tracking/bill-of-lading-bookmarks/<id>`) 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// CustomerRequest struct for CustomerRequest
type CustomerRequest struct {
	Customer string `json:"customer"`
}

// NewCustomerRequest instantiates a new CustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerRequest(customer string) *CustomerRequest {
	this := CustomerRequest{}
	this.Customer = customer
	return &this
}

// NewCustomerRequestWithDefaults instantiates a new CustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerRequestWithDefaults() *CustomerRequest {
	this := CustomerRequest{}
	return &this
}

// GetCustomer returns the Customer field value
func (o *CustomerRequest) GetCustomer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *CustomerRequest) GetCustomerOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *CustomerRequest) SetCustomer(v string) {
	o.Customer = v
}

func (o CustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["customer"] = o.Customer
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerRequest struct {
	value *CustomerRequest
	isSet bool
}

func (v NullableCustomerRequest) Get() *CustomerRequest {
	return v.value
}

func (v *NullableCustomerRequest) Set(val *CustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerRequest(val *CustomerRequest) *NullableCustomerRequest {
	return &NullableCustomerRequest{value: val, isSet: true}
}

func (v NullableCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


