/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the PostEtaBillOfLadingBookmarks400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostEtaBillOfLadingBookmarks400Response{}

// PostEtaBillOfLadingBookmarks400Response struct for PostEtaBillOfLadingBookmarks400Response
type PostEtaBillOfLadingBookmarks400Response struct {
	Message *string `json:"message,omitempty"`
}

// NewPostEtaBillOfLadingBookmarks400Response instantiates a new PostEtaBillOfLadingBookmarks400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostEtaBillOfLadingBookmarks400Response() *PostEtaBillOfLadingBookmarks400Response {
	this := PostEtaBillOfLadingBookmarks400Response{}
	return &this
}

// NewPostEtaBillOfLadingBookmarks400ResponseWithDefaults instantiates a new PostEtaBillOfLadingBookmarks400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostEtaBillOfLadingBookmarks400ResponseWithDefaults() *PostEtaBillOfLadingBookmarks400Response {
	this := PostEtaBillOfLadingBookmarks400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PostEtaBillOfLadingBookmarks400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostEtaBillOfLadingBookmarks400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PostEtaBillOfLadingBookmarks400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PostEtaBillOfLadingBookmarks400Response) SetMessage(v string) {
	o.Message = &v
}

func (o PostEtaBillOfLadingBookmarks400Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostEtaBillOfLadingBookmarks400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePostEtaBillOfLadingBookmarks400Response struct {
	value *PostEtaBillOfLadingBookmarks400Response
	isSet bool
}

func (v NullablePostEtaBillOfLadingBookmarks400Response) Get() *PostEtaBillOfLadingBookmarks400Response {
	return v.value
}

func (v *NullablePostEtaBillOfLadingBookmarks400Response) Set(val *PostEtaBillOfLadingBookmarks400Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostEtaBillOfLadingBookmarks400Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostEtaBillOfLadingBookmarks400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostEtaBillOfLadingBookmarks400Response(val *PostEtaBillOfLadingBookmarks400Response) *NullablePostEtaBillOfLadingBookmarks400Response {
	return &NullablePostEtaBillOfLadingBookmarks400Response{value: val, isSet: true}
}

func (v NullablePostEtaBillOfLadingBookmarks400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostEtaBillOfLadingBookmarks400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
