/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the GetApiV1EtaBillOfLadingBookmarksTerminals404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiV1EtaBillOfLadingBookmarksTerminals404Response{}

// GetApiV1EtaBillOfLadingBookmarksTerminals404Response struct for GetApiV1EtaBillOfLadingBookmarksTerminals404Response
type GetApiV1EtaBillOfLadingBookmarksTerminals404Response struct {
	Error *string `json:"error,omitempty"`
	Message NullableString `json:"message,omitempty"`
}

// NewGetApiV1EtaBillOfLadingBookmarksTerminals404Response instantiates a new GetApiV1EtaBillOfLadingBookmarksTerminals404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiV1EtaBillOfLadingBookmarksTerminals404Response() *GetApiV1EtaBillOfLadingBookmarksTerminals404Response {
	this := GetApiV1EtaBillOfLadingBookmarksTerminals404Response{}
	return &this
}

// NewGetApiV1EtaBillOfLadingBookmarksTerminals404ResponseWithDefaults instantiates a new GetApiV1EtaBillOfLadingBookmarksTerminals404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiV1EtaBillOfLadingBookmarksTerminals404ResponseWithDefaults() *GetApiV1EtaBillOfLadingBookmarksTerminals404Response {
	this := GetApiV1EtaBillOfLadingBookmarksTerminals404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) UnsetMessage() {
	o.Message.Unset()
}

func (o GetApiV1EtaBillOfLadingBookmarksTerminals404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiV1EtaBillOfLadingBookmarksTerminals404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response struct {
	value *GetApiV1EtaBillOfLadingBookmarksTerminals404Response
	isSet bool
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) Get() *GetApiV1EtaBillOfLadingBookmarksTerminals404Response {
	return v.value
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) Set(val *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response(val *GetApiV1EtaBillOfLadingBookmarksTerminals404Response) *NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response {
	return &NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response{value: val, isSet: true}
}

func (v NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarksTerminals404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


