/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the MessageModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageModel{}

// MessageModel struct for MessageModel
type MessageModel struct {
	Message *string `json:"message,omitempty"`
}

// NewMessageModel instantiates a new MessageModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageModel() *MessageModel {
	this := MessageModel{}
	return &this
}

// NewMessageModelWithDefaults instantiates a new MessageModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageModelWithDefaults() *MessageModel {
	this := MessageModel{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MessageModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MessageModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MessageModel) SetMessage(v string) {
	o.Message = &v
}

func (o MessageModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableMessageModel struct {
	value *MessageModel
	isSet bool
}

func (v NullableMessageModel) Get() *MessageModel {
	return v.value
}

func (v *NullableMessageModel) Set(val *MessageModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageModel(val *MessageModel) *NullableMessageModel {
	return &NullableMessageModel{value: val, isSet: true}
}

func (v NullableMessageModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
