/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the GetApiV1EtaBillOfLadingBookmarks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiV1EtaBillOfLadingBookmarks200Response{}

// GetApiV1EtaBillOfLadingBookmarks200Response Portcast Tracking Data
type GetApiV1EtaBillOfLadingBookmarks200Response struct {
	Obj *PortcastAPI `json:"obj,omitempty"`
}

// NewGetApiV1EtaBillOfLadingBookmarks200Response instantiates a new GetApiV1EtaBillOfLadingBookmarks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiV1EtaBillOfLadingBookmarks200Response() *GetApiV1EtaBillOfLadingBookmarks200Response {
	this := GetApiV1EtaBillOfLadingBookmarks200Response{}
	return &this
}

// NewGetApiV1EtaBillOfLadingBookmarks200ResponseWithDefaults instantiates a new GetApiV1EtaBillOfLadingBookmarks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiV1EtaBillOfLadingBookmarks200ResponseWithDefaults() *GetApiV1EtaBillOfLadingBookmarks200Response {
	this := GetApiV1EtaBillOfLadingBookmarks200Response{}
	return &this
}

// GetObj returns the Obj field value if set, zero value otherwise.
func (o *GetApiV1EtaBillOfLadingBookmarks200Response) GetObj() PortcastAPI {
	if o == nil || IsNil(o.Obj) {
		var ret PortcastAPI
		return ret
	}
	return *o.Obj
}

// GetObjOk returns a tuple with the Obj field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1EtaBillOfLadingBookmarks200Response) GetObjOk() (*PortcastAPI, bool) {
	if o == nil || IsNil(o.Obj) {
		return nil, false
	}
	return o.Obj, true
}

// HasObj returns a boolean if a field has been set.
func (o *GetApiV1EtaBillOfLadingBookmarks200Response) HasObj() bool {
	if o != nil && !IsNil(o.Obj) {
		return true
	}

	return false
}

// SetObj gets a reference to the given PortcastAPI and assigns it to the Obj field.
func (o *GetApiV1EtaBillOfLadingBookmarks200Response) SetObj(v PortcastAPI) {
	o.Obj = &v
}

func (o GetApiV1EtaBillOfLadingBookmarks200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiV1EtaBillOfLadingBookmarks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Obj) {
		toSerialize["obj"] = o.Obj
	}
	return toSerialize, nil
}

type NullableGetApiV1EtaBillOfLadingBookmarks200Response struct {
	value *GetApiV1EtaBillOfLadingBookmarks200Response
	isSet bool
}

func (v NullableGetApiV1EtaBillOfLadingBookmarks200Response) Get() *GetApiV1EtaBillOfLadingBookmarks200Response {
	return v.value
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarks200Response) Set(val *GetApiV1EtaBillOfLadingBookmarks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiV1EtaBillOfLadingBookmarks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiV1EtaBillOfLadingBookmarks200Response(val *GetApiV1EtaBillOfLadingBookmarks200Response) *NullableGetApiV1EtaBillOfLadingBookmarks200Response {
	return &NullableGetApiV1EtaBillOfLadingBookmarks200Response{value: val, isSet: true}
}

func (v NullableGetApiV1EtaBillOfLadingBookmarks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiV1EtaBillOfLadingBookmarks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
