/*
Portcast API (1.1.0) - Bill of Lading Tracking

**This documentation is for the latest version of the Portcast Bill of Lading Tracking API.**  There are two variables used in this documentation: 1. `api-url`: the url to use for accessing the API. The official url is `https://api.portcast.io` 2. `x-api-key`: the access token to send along with every request to the API. This key will be provided to each organisation upon API access activation  The general workflow is as below:  1. Create the bill of lading bookmark if it does not exist already (`POST {{api-url}}/api/v1/eta/bill-of-lading-bookmarks`). 2. A bookmark must contain `carrier_no`, `bl_no` and `cntr_no` information. This will return the bill of lading bookmark information created. Record the `id` field from the response. 3. Wait for predictions to be generated. This could take up to 5 mins. 5. Query for the tracking results based on the `id` recorded earlier (`GET {{api-url}}/api/v1/eta/tracking/bill-of-lading-bookmarks/<id>`) 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
	"time"
)

// Bookmark struct for Bookmark
type Bookmark struct {
	BlNo *string `json:"bl_no,omitempty"`
	CarrierNo *string `json:"carrier_no,omitempty"`
	CntrNo *string `json:"cntr_no,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	CustomerNo *string `json:"customer_no,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
	Id *string `json:"id,omitempty"`
	OrgId *string `json:"org_id,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusCode *string `json:"status_code,omitempty"`
	SystemDeleted *bool `json:"system_deleted,omitempty"`
	Updated *time.Time `json:"updated,omitempty"`
	VesselList *[]string `json:"vessel_list,omitempty"`
	VoyageNo *string `json:"voyage_no,omitempty"`
}

// NewBookmark instantiates a new Bookmark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmark() *Bookmark {
	this := Bookmark{}
	return &this
}

// NewBookmarkWithDefaults instantiates a new Bookmark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarkWithDefaults() *Bookmark {
	this := Bookmark{}
	return &this
}

// GetBlNo returns the BlNo field value if set, zero value otherwise.
func (o *Bookmark) GetBlNo() string {
	if o == nil || o.BlNo == nil {
		var ret string
		return ret
	}
	return *o.BlNo
}

// GetBlNoOk returns a tuple with the BlNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetBlNoOk() (*string, bool) {
	if o == nil || o.BlNo == nil {
		return nil, false
	}
	return o.BlNo, true
}

// HasBlNo returns a boolean if a field has been set.
func (o *Bookmark) HasBlNo() bool {
	if o != nil && o.BlNo != nil {
		return true
	}

	return false
}

// SetBlNo gets a reference to the given string and assigns it to the BlNo field.
func (o *Bookmark) SetBlNo(v string) {
	o.BlNo = &v
}

// GetCarrierNo returns the CarrierNo field value if set, zero value otherwise.
func (o *Bookmark) GetCarrierNo() string {
	if o == nil || o.CarrierNo == nil {
		var ret string
		return ret
	}
	return *o.CarrierNo
}

// GetCarrierNoOk returns a tuple with the CarrierNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCarrierNoOk() (*string, bool) {
	if o == nil || o.CarrierNo == nil {
		return nil, false
	}
	return o.CarrierNo, true
}

// HasCarrierNo returns a boolean if a field has been set.
func (o *Bookmark) HasCarrierNo() bool {
	if o != nil && o.CarrierNo != nil {
		return true
	}

	return false
}

// SetCarrierNo gets a reference to the given string and assigns it to the CarrierNo field.
func (o *Bookmark) SetCarrierNo(v string) {
	o.CarrierNo = &v
}

// GetCntrNo returns the CntrNo field value if set, zero value otherwise.
func (o *Bookmark) GetCntrNo() string {
	if o == nil || o.CntrNo == nil {
		var ret string
		return ret
	}
	return *o.CntrNo
}

// GetCntrNoOk returns a tuple with the CntrNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCntrNoOk() (*string, bool) {
	if o == nil || o.CntrNo == nil {
		return nil, false
	}
	return o.CntrNo, true
}

// HasCntrNo returns a boolean if a field has been set.
func (o *Bookmark) HasCntrNo() bool {
	if o != nil && o.CntrNo != nil {
		return true
	}

	return false
}

// SetCntrNo gets a reference to the given string and assigns it to the CntrNo field.
func (o *Bookmark) SetCntrNo(v string) {
	o.CntrNo = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Bookmark) GetCreated() time.Time {
	if o == nil || o.Created == nil {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCreatedOk() (*time.Time, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Bookmark) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Bookmark) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *Bookmark) GetCustomerId() string {
	if o == nil || o.CustomerId == nil {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCustomerIdOk() (*string, bool) {
	if o == nil || o.CustomerId == nil {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *Bookmark) HasCustomerId() bool {
	if o != nil && o.CustomerId != nil {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *Bookmark) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetCustomerNo returns the CustomerNo field value if set, zero value otherwise.
func (o *Bookmark) GetCustomerNo() string {
	if o == nil || o.CustomerNo == nil {
		var ret string
		return ret
	}
	return *o.CustomerNo
}

// GetCustomerNoOk returns a tuple with the CustomerNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCustomerNoOk() (*string, bool) {
	if o == nil || o.CustomerNo == nil {
		return nil, false
	}
	return o.CustomerNo, true
}

// HasCustomerNo returns a boolean if a field has been set.
func (o *Bookmark) HasCustomerNo() bool {
	if o != nil && o.CustomerNo != nil {
		return true
	}

	return false
}

// SetCustomerNo gets a reference to the given string and assigns it to the CustomerNo field.
func (o *Bookmark) SetCustomerNo(v string) {
	o.CustomerNo = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *Bookmark) GetDeleted() bool {
	if o == nil || o.Deleted == nil {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetDeletedOk() (*bool, bool) {
	if o == nil || o.Deleted == nil {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *Bookmark) HasDeleted() bool {
	if o != nil && o.Deleted != nil {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *Bookmark) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Bookmark) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Bookmark) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Bookmark) SetId(v string) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *Bookmark) GetOrgId() string {
	if o == nil || o.OrgId == nil {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetOrgIdOk() (*string, bool) {
	if o == nil || o.OrgId == nil {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *Bookmark) HasOrgId() bool {
	if o != nil && o.OrgId != nil {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *Bookmark) SetOrgId(v string) {
	o.OrgId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Bookmark) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Bookmark) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Bookmark) SetStatus(v string) {
	o.Status = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *Bookmark) GetStatusCode() string {
	if o == nil || o.StatusCode == nil {
		var ret string
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetStatusCodeOk() (*string, bool) {
	if o == nil || o.StatusCode == nil {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *Bookmark) HasStatusCode() bool {
	if o != nil && o.StatusCode != nil {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given string and assigns it to the StatusCode field.
func (o *Bookmark) SetStatusCode(v string) {
	o.StatusCode = &v
}

// GetSystemDeleted returns the SystemDeleted field value if set, zero value otherwise.
func (o *Bookmark) GetSystemDeleted() bool {
	if o == nil || o.SystemDeleted == nil {
		var ret bool
		return ret
	}
	return *o.SystemDeleted
}

// GetSystemDeletedOk returns a tuple with the SystemDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetSystemDeletedOk() (*bool, bool) {
	if o == nil || o.SystemDeleted == nil {
		return nil, false
	}
	return o.SystemDeleted, true
}

// HasSystemDeleted returns a boolean if a field has been set.
func (o *Bookmark) HasSystemDeleted() bool {
	if o != nil && o.SystemDeleted != nil {
		return true
	}

	return false
}

// SetSystemDeleted gets a reference to the given bool and assigns it to the SystemDeleted field.
func (o *Bookmark) SetSystemDeleted(v bool) {
	o.SystemDeleted = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Bookmark) GetUpdated() time.Time {
	if o == nil || o.Updated == nil {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || o.Updated == nil {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Bookmark) HasUpdated() bool {
	if o != nil && o.Updated != nil {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Bookmark) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetVesselList returns the VesselList field value if set, zero value otherwise.
func (o *Bookmark) GetVesselList() []string {
	if o == nil || o.VesselList == nil {
		var ret []string
		return ret
	}
	return *o.VesselList
}

// GetVesselListOk returns a tuple with the VesselList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetVesselListOk() (*[]string, bool) {
	if o == nil || o.VesselList == nil {
		return nil, false
	}
	return o.VesselList, true
}

// HasVesselList returns a boolean if a field has been set.
func (o *Bookmark) HasVesselList() bool {
	if o != nil && o.VesselList != nil {
		return true
	}

	return false
}

// SetVesselList gets a reference to the given []string and assigns it to the VesselList field.
func (o *Bookmark) SetVesselList(v []string) {
	o.VesselList = &v
}

// GetVoyageNo returns the VoyageNo field value if set, zero value otherwise.
func (o *Bookmark) GetVoyageNo() string {
	if o == nil || o.VoyageNo == nil {
		var ret string
		return ret
	}
	return *o.VoyageNo
}

// GetVoyageNoOk returns a tuple with the VoyageNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetVoyageNoOk() (*string, bool) {
	if o == nil || o.VoyageNo == nil {
		return nil, false
	}
	return o.VoyageNo, true
}

// HasVoyageNo returns a boolean if a field has been set.
func (o *Bookmark) HasVoyageNo() bool {
	if o != nil && o.VoyageNo != nil {
		return true
	}

	return false
}

// SetVoyageNo gets a reference to the given string and assigns it to the VoyageNo field.
func (o *Bookmark) SetVoyageNo(v string) {
	o.VoyageNo = &v
}

func (o Bookmark) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BlNo != nil {
		toSerialize["bl_no"] = o.BlNo
	}
	if o.CarrierNo != nil {
		toSerialize["carrier_no"] = o.CarrierNo
	}
	if o.CntrNo != nil {
		toSerialize["cntr_no"] = o.CntrNo
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.CustomerId != nil {
		toSerialize["customer_id"] = o.CustomerId
	}
	if o.CustomerNo != nil {
		toSerialize["customer_no"] = o.CustomerNo
	}
	if o.Deleted != nil {
		toSerialize["deleted"] = o.Deleted
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.OrgId != nil {
		toSerialize["org_id"] = o.OrgId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StatusCode != nil {
		toSerialize["status_code"] = o.StatusCode
	}
	if o.SystemDeleted != nil {
		toSerialize["system_deleted"] = o.SystemDeleted
	}
	if o.Updated != nil {
		toSerialize["updated"] = o.Updated
	}
	if o.VesselList != nil {
		toSerialize["vessel_list"] = o.VesselList
	}
	if o.VoyageNo != nil {
		toSerialize["voyage_no"] = o.VoyageNo
	}
	return json.Marshal(toSerialize)
}

type NullableBookmark struct {
	value *Bookmark
	isSet bool
}

func (v NullableBookmark) Get() *Bookmark {
	return v.value
}

func (v *NullableBookmark) Set(val *Bookmark) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmark) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmark(val *Bookmark) *NullableBookmark {
	return &NullableBookmark{value: val, isSet: true}
}

func (v NullableBookmark) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmark) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


