/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
	"time"
)

// checks if the BillOfLadingBookmark type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillOfLadingBookmark{}

// BillOfLadingBookmark Schema for the Bill of Lading Bookmark Object
type BillOfLadingBookmark struct {
	// Bill of Lading No or Booking No.
	BlNo NullableString `json:"bl_no,omitempty"`
	// Carrier SCAC Code
	CarrierNo *string `json:"carrier_no,omitempty"`
	// Container Number
	CntrNo *string `json:"cntr_no,omitempty"`
	// Bookmark Upload Date
	Created *time.Time `json:"created,omitempty"`
	// Archival Status of the bookmark
	Deleted *bool `json:"deleted,omitempty"`
	// Unique Identifier called Bill of Lading Bookmark ID [Primary Key] (Also refered as Bookmark ID)
	Id *string `json:"id,omitempty"`
	// Customer Org (Flow) to which the bookmark ID is uploaded too
	OrgId *string `json:"org_id,omitempty"`
	// [Deprecated] Old Status codes - Not supported
	// Deprecated
	Status *string `json:"status,omitempty"`
	// [Depricated] Old Status codes - Not supported
	// Deprecated
	StatusCode *string `json:"status_code,omitempty"`
	StatusInfo *BillOfLadingBookmarkStatusInfo `json:"status_info,omitempty"`
	// System Deletion Status of the bookmark
	SystemDeleted *bool `json:"system_deleted,omitempty"`
	// Last Updated date for the Bookmark ID (Refers to when we fetched the latest data for the bookmark ID)
	Updated *time.Time `json:"updated,omitempty"`
}

// NewBillOfLadingBookmark instantiates a new BillOfLadingBookmark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillOfLadingBookmark() *BillOfLadingBookmark {
	this := BillOfLadingBookmark{}
	var deleted bool = false
	this.Deleted = &deleted
	var systemDeleted bool = false
	this.SystemDeleted = &systemDeleted
	return &this
}

// NewBillOfLadingBookmarkWithDefaults instantiates a new BillOfLadingBookmark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillOfLadingBookmarkWithDefaults() *BillOfLadingBookmark {
	this := BillOfLadingBookmark{}
	var deleted bool = false
	this.Deleted = &deleted
	var systemDeleted bool = false
	this.SystemDeleted = &systemDeleted
	return &this
}

// GetBlNo returns the BlNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BillOfLadingBookmark) GetBlNo() string {
	if o == nil || IsNil(o.BlNo.Get()) {
		var ret string
		return ret
	}
	return *o.BlNo.Get()
}

// GetBlNoOk returns a tuple with the BlNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillOfLadingBookmark) GetBlNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlNo.Get(), o.BlNo.IsSet()
}

// HasBlNo returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasBlNo() bool {
	if o != nil && o.BlNo.IsSet() {
		return true
	}

	return false
}

// SetBlNo gets a reference to the given NullableString and assigns it to the BlNo field.
func (o *BillOfLadingBookmark) SetBlNo(v string) {
	o.BlNo.Set(&v)
}
// SetBlNoNil sets the value for BlNo to be an explicit nil
func (o *BillOfLadingBookmark) SetBlNoNil() {
	o.BlNo.Set(nil)
}

// UnsetBlNo ensures that no value is present for BlNo, not even an explicit nil
func (o *BillOfLadingBookmark) UnsetBlNo() {
	o.BlNo.Unset()
}

// GetCarrierNo returns the CarrierNo field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetCarrierNo() string {
	if o == nil || IsNil(o.CarrierNo) {
		var ret string
		return ret
	}
	return *o.CarrierNo
}

// GetCarrierNoOk returns a tuple with the CarrierNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetCarrierNoOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierNo) {
		return nil, false
	}
	return o.CarrierNo, true
}

// HasCarrierNo returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasCarrierNo() bool {
	if o != nil && !IsNil(o.CarrierNo) {
		return true
	}

	return false
}

// SetCarrierNo gets a reference to the given string and assigns it to the CarrierNo field.
func (o *BillOfLadingBookmark) SetCarrierNo(v string) {
	o.CarrierNo = &v
}

// GetCntrNo returns the CntrNo field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetCntrNo() string {
	if o == nil || IsNil(o.CntrNo) {
		var ret string
		return ret
	}
	return *o.CntrNo
}

// GetCntrNoOk returns a tuple with the CntrNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetCntrNoOk() (*string, bool) {
	if o == nil || IsNil(o.CntrNo) {
		return nil, false
	}
	return o.CntrNo, true
}

// HasCntrNo returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasCntrNo() bool {
	if o != nil && !IsNil(o.CntrNo) {
		return true
	}

	return false
}

// SetCntrNo gets a reference to the given string and assigns it to the CntrNo field.
func (o *BillOfLadingBookmark) SetCntrNo(v string) {
	o.CntrNo = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *BillOfLadingBookmark) SetCreated(v time.Time) {
	o.Created = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *BillOfLadingBookmark) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BillOfLadingBookmark) SetId(v string) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *BillOfLadingBookmark) SetOrgId(v string) {
	o.OrgId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
// Deprecated
func (o *BillOfLadingBookmark) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BillOfLadingBookmark) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
// Deprecated
func (o *BillOfLadingBookmark) SetStatus(v string) {
	o.Status = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
// Deprecated
func (o *BillOfLadingBookmark) GetStatusCode() string {
	if o == nil || IsNil(o.StatusCode) {
		var ret string
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BillOfLadingBookmark) GetStatusCodeOk() (*string, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given string and assigns it to the StatusCode field.
// Deprecated
func (o *BillOfLadingBookmark) SetStatusCode(v string) {
	o.StatusCode = &v
}

// GetStatusInfo returns the StatusInfo field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetStatusInfo() BillOfLadingBookmarkStatusInfo {
	if o == nil || IsNil(o.StatusInfo) {
		var ret BillOfLadingBookmarkStatusInfo
		return ret
	}
	return *o.StatusInfo
}

// GetStatusInfoOk returns a tuple with the StatusInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetStatusInfoOk() (*BillOfLadingBookmarkStatusInfo, bool) {
	if o == nil || IsNil(o.StatusInfo) {
		return nil, false
	}
	return o.StatusInfo, true
}

// HasStatusInfo returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasStatusInfo() bool {
	if o != nil && !IsNil(o.StatusInfo) {
		return true
	}

	return false
}

// SetStatusInfo gets a reference to the given BillOfLadingBookmarkStatusInfo and assigns it to the StatusInfo field.
func (o *BillOfLadingBookmark) SetStatusInfo(v BillOfLadingBookmarkStatusInfo) {
	o.StatusInfo = &v
}

// GetSystemDeleted returns the SystemDeleted field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetSystemDeleted() bool {
	if o == nil || IsNil(o.SystemDeleted) {
		var ret bool
		return ret
	}
	return *o.SystemDeleted
}

// GetSystemDeletedOk returns a tuple with the SystemDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetSystemDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.SystemDeleted) {
		return nil, false
	}
	return o.SystemDeleted, true
}

// HasSystemDeleted returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasSystemDeleted() bool {
	if o != nil && !IsNil(o.SystemDeleted) {
		return true
	}

	return false
}

// SetSystemDeleted gets a reference to the given bool and assigns it to the SystemDeleted field.
func (o *BillOfLadingBookmark) SetSystemDeleted(v bool) {
	o.SystemDeleted = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *BillOfLadingBookmark) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillOfLadingBookmark) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *BillOfLadingBookmark) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *BillOfLadingBookmark) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o BillOfLadingBookmark) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillOfLadingBookmark) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BlNo.IsSet() {
		toSerialize["bl_no"] = o.BlNo.Get()
	}
	if !IsNil(o.CarrierNo) {
		toSerialize["carrier_no"] = o.CarrierNo
	}
	if !IsNil(o.CntrNo) {
		toSerialize["cntr_no"] = o.CntrNo
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.StatusInfo) {
		toSerialize["status_info"] = o.StatusInfo
	}
	if !IsNil(o.SystemDeleted) {
		toSerialize["system_deleted"] = o.SystemDeleted
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableBillOfLadingBookmark struct {
	value *BillOfLadingBookmark
	isSet bool
}

func (v NullableBillOfLadingBookmark) Get() *BillOfLadingBookmark {
	return v.value
}

func (v *NullableBillOfLadingBookmark) Set(val *BillOfLadingBookmark) {
	v.value = val
	v.isSet = true
}

func (v NullableBillOfLadingBookmark) IsSet() bool {
	return v.isSet
}

func (v *NullableBillOfLadingBookmark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillOfLadingBookmark(val *BillOfLadingBookmark) *NullableBillOfLadingBookmark {
	return &NullableBillOfLadingBookmark{value: val, isSet: true}
}

func (v NullableBillOfLadingBookmark) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillOfLadingBookmark) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


