/*
Container Tracking API

This documentation defines how the users can utilize the Portcast API to retrieve the latest Track and Trace Data for any container, bill of lading or booking across 100+ carriers and 2500+ ports across the globe.  What's changed in the version 2.0? Find out more about it [here](https://support.portcast.io/support/solutions/articles/151000074289-api-release-notes-april-2023-)!!

API version: 2.0
Contact: support@portcast.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package portcast

import (
	"encoding/json"
)

// checks if the BookingAPIResponseInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookingAPIResponseInnerAnyOf{}

// BookingAPIResponseInnerAnyOf Bill of Lading Bookmark Object
type BookingAPIResponseInnerAnyOf struct {
	// Bill of Lading Bookmark Object
	Obj *BillOfLadingBookmark `json:"obj,omitempty"`
	// Status of the individual container upload
	Status *string `json:"status,omitempty"`
	// Container Number registered under the BL/Booking
	Container *string `json:"container,omitempty"`
}

// NewBookingAPIResponseInnerAnyOf instantiates a new BookingAPIResponseInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookingAPIResponseInnerAnyOf() *BookingAPIResponseInnerAnyOf {
	this := BookingAPIResponseInnerAnyOf{}
	return &this
}

// NewBookingAPIResponseInnerAnyOfWithDefaults instantiates a new BookingAPIResponseInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookingAPIResponseInnerAnyOfWithDefaults() *BookingAPIResponseInnerAnyOf {
	this := BookingAPIResponseInnerAnyOf{}
	return &this
}

// GetObj returns the Obj field value if set, zero value otherwise.
func (o *BookingAPIResponseInnerAnyOf) GetObj() BillOfLadingBookmark {
	if o == nil || IsNil(o.Obj) {
		var ret BillOfLadingBookmark
		return ret
	}
	return *o.Obj
}

// GetObjOk returns a tuple with the Obj field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingAPIResponseInnerAnyOf) GetObjOk() (*BillOfLadingBookmark, bool) {
	if o == nil || IsNil(o.Obj) {
		return nil, false
	}
	return o.Obj, true
}

// HasObj returns a boolean if a field has been set.
func (o *BookingAPIResponseInnerAnyOf) HasObj() bool {
	if o != nil && !IsNil(o.Obj) {
		return true
	}

	return false
}

// SetObj gets a reference to the given BillOfLadingBookmark and assigns it to the Obj field.
func (o *BookingAPIResponseInnerAnyOf) SetObj(v BillOfLadingBookmark) {
	o.Obj = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BookingAPIResponseInnerAnyOf) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingAPIResponseInnerAnyOf) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BookingAPIResponseInnerAnyOf) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BookingAPIResponseInnerAnyOf) SetStatus(v string) {
	o.Status = &v
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *BookingAPIResponseInnerAnyOf) GetContainer() string {
	if o == nil || IsNil(o.Container) {
		var ret string
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingAPIResponseInnerAnyOf) GetContainerOk() (*string, bool) {
	if o == nil || IsNil(o.Container) {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *BookingAPIResponseInnerAnyOf) HasContainer() bool {
	if o != nil && !IsNil(o.Container) {
		return true
	}

	return false
}

// SetContainer gets a reference to the given string and assigns it to the Container field.
func (o *BookingAPIResponseInnerAnyOf) SetContainer(v string) {
	o.Container = &v
}

func (o BookingAPIResponseInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookingAPIResponseInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Obj) {
		toSerialize["obj"] = o.Obj
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Container) {
		toSerialize["container"] = o.Container
	}
	return toSerialize, nil
}

type NullableBookingAPIResponseInnerAnyOf struct {
	value *BookingAPIResponseInnerAnyOf
	isSet bool
}

func (v NullableBookingAPIResponseInnerAnyOf) Get() *BookingAPIResponseInnerAnyOf {
	return v.value
}

func (v *NullableBookingAPIResponseInnerAnyOf) Set(val *BookingAPIResponseInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBookingAPIResponseInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBookingAPIResponseInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookingAPIResponseInnerAnyOf(val *BookingAPIResponseInnerAnyOf) *NullableBookingAPIResponseInnerAnyOf {
	return &NullableBookingAPIResponseInnerAnyOf{value: val, isSet: true}
}

func (v NullableBookingAPIResponseInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookingAPIResponseInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


